"""Phrases composées (verbe + objet + contexte) des annonces synthétiques.

Les réserves de phrases entières restent petites : un modèle lexical finit par les mémoriser et
juge suspecte toute phrase légitime qu'il n'a jamais vue. Composer des missions et des exigences à
partir de listes de verbes, d'objets et de contextes multiplie les tournures vues à l'entraînement,
et le partage des listes (`split_pool`) garde l'évaluation sur des mots et combinaisons inédits.
"""

from __future__ import annotations

FR_VERBS = (
    "Concevoir",
    "Mettre à jour",
    "Coordonner",
    "Analyser",
    "Documenter",
    "Planifier",
    "Superviser",
    "Optimiser",
    "Évaluer",
    "Piloter",
    "Déployer",
    "Réviser",
    "Préparer",
    "Suivre",
    "Améliorer",
    "Valider",
    "Organiser",
    "Soutenir",
    "Tester",
    "Présenter",
    "Négocier",
    "Automatiser",
    "Contrôler",
    "Standardiser",
    "Rédiger",
    "Accompagner le déploiement de",
    "Participer à la conception de",
    "Veiller à la qualité de",
    "Assurer le suivi de",
    "Proposer des améliorations pour",
    "Moderniser",
    "Consolider",
    "Prioriser",
    "Cartographier",
    "Mesurer l'efficacité de",
    "Simplifier",
)
FR_OBJECTS = (
    "les tableaux de bord de suivi",
    "le budget annuel du service",
    "les procédures d'accueil",
    "les flux de données clients",
    "le calendrier des livraisons",
    "les contrats de sous-traitance",
    "les campagnes de sensibilisation",
    "les indicateurs de performance",
    "l'inventaire des équipements",
    "les dossiers de conformité",
    "les demandes de soutien technique",
    "la documentation des processus",
    "le plan de formation",
    "les rapports mensuels",
    "les outils de planification",
    "la relation avec les fournisseurs",
    "les tests d'acceptation",
    "le programme de mentorat",
    "les interfaces de programmation",
    "les modèles de prévision",
    "les pipelines de déploiement",
    "le parcours client en ligne",
    "les ententes de service",
    "les demandes de subvention",
    "le registre des risques",
    "la gestion des stocks",
    "les horaires des équipes",
    "les audits de sécurité",
    "les réclamations des clients",
    "les projets d'amélioration continue",
    "la base de connaissances interne",
    "les contrôles de qualité",
    "les appels d'offres",
    "les communications internes",
    "l'architecture des applications",
    "les tableaux de coûts",
    "les processus de facturation",
    "le programme de santé et sécurité",
    "les plans d'entretien",
    "les ateliers de cocréation",
    "les données de géolocalisation",
    "le catalogue de services",
    "les formulaires en ligne",
    "le suivi des incidents",
    "la feuille de route du produit",
    "les requêtes d'analyse",
    "les maquettes d'interface",
    "les politiques internes",
)
FR_CONTEXTS = (
    "avec les équipes concernées",
    "dans le respect des échéanciers",
    "selon les priorités établies avec la direction",
    "pour nos clients institutionnels",
    "en lien avec le service des finances",
    "dans un environnement en forte croissance",
    "à l'échelle de la province",
    "pour l'ensemble des succursales",
    "en tenant compte des besoins des usagers",
    "dans un souci d'amélioration continue",
    "avec l'appui d'un comité de pilotage",
    "sur plusieurs sites",
    "au sein d'une équipe multidisciplinaire",
    "en mode agile",
    "avec des partenaires externes",
    "tout en respectant les normes en vigueur",
    "pour réduire les délais de traitement",
    "afin d'améliorer l'expérience client",
    "en collaboration avec les TI",
    "de la conception à la mise en service",
    "dans les délais convenus",
    "en fonction des résultats obtenus",
    "pour les besoins de la direction",
    "pour soutenir la croissance de l'entreprise",
    "dans le cadre du plan stratégique",
    "auprès des gestionnaires de premier niveau",
    "en assurant une reddition de comptes rigoureuse",
    "en vue de l'audit annuel",
    "pour le marché canadien",
    "de façon autonome",
)
FR_SKILL_LEADS = (
    "Expérience démontrée en",
    "Bonne connaissance de",
    "Maîtrise de",
    "Au moins trois ans d'expérience en",
    "Formation en",
    "Intérêt marqué pour",
    "Connaissance pratique de",
    "Solide expérience en",
    "Aisance avec",
    "Familiarité avec",
)
FR_SKILL_TOPICS = (
    "la gestion de projets",
    "l'analyse de données",
    "la relation client",
    "la comptabilité de gestion",
    "la gestion du changement",
    "la planification financière",
    "les méthodes agiles",
    "la programmation orientée objet",
    "la gestion de la qualité",
    "l'infonuagique",
    "la chaîne d'approvisionnement",
    "la rédaction technique",
    "la négociation commerciale",
    "l'animation de groupes",
    "la santé et sécurité au travail",
    "la réglementation municipale",
    "le soutien aux utilisateurs",
    "la gestion documentaire",
    "l'amélioration des processus",
    "la cybersécurité",
    "la gestion budgétaire",
    "les bases de données relationnelles",
    "la conception centrée sur l'utilisateur",
    "la communication organisationnelle",
)

EN_VERBS = (
    "Design",
    "Update",
    "Coordinate",
    "Analyze",
    "Document",
    "Plan",
    "Supervise",
    "Optimize",
    "Assess",
    "Lead",
    "Deploy",
    "Review",
    "Prepare",
    "Track",
    "Improve",
    "Validate",
    "Organize",
    "Support",
    "Test",
    "Present",
    "Negotiate",
    "Automate",
    "Audit",
    "Standardize",
    "Draft",
    "Help roll out",
    "Contribute to the design of",
    "Ensure the quality of",
    "Follow up on",
    "Propose improvements to",
    "Modernize",
    "Consolidate",
    "Prioritize",
    "Map",
    "Measure the effectiveness of",
    "Simplify",
)
EN_OBJECTS = (
    "the monitoring dashboards",
    "the department's annual budget",
    "onboarding procedures",
    "customer data flows",
    "the delivery calendar",
    "subcontracting agreements",
    "awareness campaigns",
    "performance indicators",
    "the equipment inventory",
    "compliance files",
    "technical support requests",
    "process documentation",
    "the training plan",
    "monthly reports",
    "planning tools",
    "supplier relationships",
    "acceptance tests",
    "the mentoring program",
    "application programming interfaces",
    "forecasting models",
    "deployment pipelines",
    "the online customer journey",
    "service level agreements",
    "grant applications",
    "the risk register",
    "inventory management",
    "team schedules",
    "security audits",
    "customer claims",
    "continuous improvement projects",
    "the internal knowledge base",
    "quality controls",
    "requests for proposals",
    "internal communications",
    "the application architecture",
    "cost spreadsheets",
    "billing processes",
    "the health and safety program",
    "maintenance plans",
    "co-design workshops",
    "geolocation data",
    "the service catalogue",
    "online forms",
    "incident tracking",
    "the product roadmap",
    "analytics queries",
    "interface mock-ups",
    "internal policies",
)
EN_CONTEXTS = (
    "with the relevant teams",
    "on schedule",
    "based on priorities set with leadership",
    "for our institutional clients",
    "together with the finance department",
    "in a fast-growing environment",
    "across the province",
    "for every branch",
    "with end users' needs in mind",
    "with a focus on continuous improvement",
    "with the support of a steering committee",
    "across several sites",
    "within a multidisciplinary team",
    "in an agile setting",
    "with external partners",
    "in line with current standards",
    "to cut processing times",
    "to improve the customer experience",
    "in collaboration with IT",
    "from design to commissioning",
    "within agreed timelines",
    "based on the results achieved",
    "for senior management",
    "to support the company's growth",
    "as part of the strategic plan",
    "with front-line managers",
    "with rigorous accountability",
    "ahead of the annual audit",
    "for the Canadian market",
    "independently",
)
EN_SKILL_LEADS = (
    "Proven experience in",
    "Good knowledge of",
    "Command of",
    "At least three years of experience in",
    "Training in",
    "Strong interest in",
    "Hands-on knowledge of",
    "Solid background in",
    "Comfortable with",
    "Familiarity with",
)
EN_SKILL_TOPICS = (
    "project management",
    "data analysis",
    "customer relations",
    "management accounting",
    "change management",
    "financial planning",
    "agile methods",
    "object-oriented programming",
    "quality management",
    "cloud computing",
    "supply chain",
    "technical writing",
    "commercial negotiation",
    "group facilitation",
    "occupational health and safety",
    "municipal regulations",
    "user support",
    "records management",
    "process improvement",
    "cybersecurity",
    "budget management",
    "relational databases",
    "user-centred design",
    "organizational communication",
)
