"""English phrase bank for the synthetic job ads (all invented, no real data).

Each pool is split between training and evaluation by `ml.job_ads.split_pool`: evaluation ads
never use a sentence seen in training.
"""

from __future__ import annotations

from ml.job_ads_types import Sector

SECTORS: tuple[Sector, ...] = (
    Sector(
        "ai",
        (
            "Generative AI Architect",
            "Machine Learning Engineer",
            "Staff Applied Scientist",
            "LLM Platform Engineer",
            "MLOps Lead",
            "Conversational AI Developer",
        ),
        (
            "Design LLM-based assistants and the guardrails around them.",
            "Build retrieval-augmented generation (RAG) over our internal knowledge bases.",
            "Evaluate model answers with versioned test suites and human review.",
            "Automate model training, packaging and deployment in the cloud.",
            "Write and maintain the system prompts of our assistants, reviewed by compliance.",
            "Monitor production drift and plan retraining.",
            "Help business teams identify where AI actually adds value.",
            "Define content filtering rules and test them against known attacks.",
            "Choose between hosted and open-weight models based on cost and privacy.",
            "Document architecture decisions and present them to the technical review board.",
            "Track latency and cost per request for every deployed agent.",
            "Coach developers on prompt engineering best practices.",
            "Build input filtering against prompt injection and validate model outputs.",
            "Organize red-team exercises on our assistants before each production release.",
            "Version system prompts and evaluation sets the same way we version code.",
            "Design an agent platform that lets teams combine tools, prompts and workflows.",
            "Define guardrails for each AI feature: personal data protection, usage limits, "
            "logging.",
            "Instrument agents (traces, cost, latency) and publish quality dashboards.",
            "Assess model resistance to jailbreak attempts and document the fixes.",
            "Govern the tools that agents can call: least privilege and human approval.",
            "Automate regression suites that replay typical conversations on every change.",
            "Write the responsible generative AI policy together with the legal team.",
            "Compare the answers of several language models on our real use cases.",
            "Set up drift detection and alerts on answer quality.",
        ),
        (
            "Five or more years of software development, including two in machine learning.",
            "Strong Python skills and familiarity with the usual ML libraries.",
            "Hands-on experience shipping language models to production.",
            "Solid understanding of generative AI risks: hallucination, prompt injection, data "
            "leakage.",
            "Ability to explain technical trade-offs to non-technical managers.",
            "Degree in computer science, engineering or a related field.",
            "Familiarity with AI governance frameworks is an asset.",
            "Comfort with statistical model evaluation.",
            "Experience with event-driven architectures is a plus.",
        ),
        (
            "Python",
            "PyTorch",
            "AWS Bedrock",
            "Azure OpenAI",
            "LangGraph",
            "PostgreSQL with pgvector",
            "Docker",
            "GitHub Actions",
            "Weights & Biases",
            "FastAPI",
            "Terraform",
            "OpenTelemetry",
        ),
    ),
    Sector(
        "software",
        (
            "Senior Backend Developer",
            "Full Stack Engineer",
            "Software Architect",
            "Site Reliability Engineer",
            "Engineering Team Lead",
            "DevOps Engineer",
        ),
        (
            "Build new features for our online booking platform.",
            "Take part in code reviews and mentor junior developers.",
            "Raise automated test coverage and overall code quality.",
            "Maintain the continuous integration and delivery pipelines.",
            "Troubleshoot production incidents and write blameless post-mortems.",
            "Design robust, well-documented REST and gRPC APIs.",
            "Pay down technical debt together with the product owner.",
            "Tune the most expensive database queries.",
            "Automate infrastructure provisioning.",
            "Set up observability: logs, metrics and traces.",
            "Contribute to the team's technology choices.",
            "Join a rotating on-call schedule, one week in six.",
        ),
        (
            "Three or more years of professional development experience.",
            "Good knowledge of a typed language such as Java, Kotlin, Go or TypeScript.",
            "Used to agile methods and small iterations.",
            "Attention to detail and a taste for readable code.",
            "Experience with containers and their orchestration.",
            "Fluent written and spoken English; French is an asset.",
            "Curiosity about application security.",
            "Able to manage your own priorities.",
            "Experience with a high-traffic product is a plus.",
        ),
        (
            "Java",
            "Kotlin",
            "TypeScript",
            "React",
            "Kubernetes",
            "Kafka",
            "Redis",
            "PostgreSQL",
            "Grafana",
            "CircleCI",
            "Go",
            "gRPC",
        ),
    ),
    Sector(
        "health",
        (
            "Registered Nurse",
            "Home Care Coordinator",
            "Medical Imaging Technologist",
            "Hospital Pharmacist",
            "Nurse Manager",
            "Respiratory Therapist",
        ),
        (
            "Assess patients and adjust care plans as their condition evolves.",
            "Work closely with physicians, physiotherapists and social workers.",
            "Follow up with patients after discharge.",
            "Perform exams according to current radiation safety protocols.",
            "Contribute to quality and patient safety initiatives.",
            "Supervise students and newly hired staff.",
            "Keep electronic health records accurate and up to date.",
            "Prepare and verify prescriptions with the medical team.",
            "Schedule the team and ensure continuity of care.",
            "Inform families and answer their questions with empathy.",
            "Support infection prevention projects.",
            "Sit on interdisciplinary committees.",
        ),
        (
            "Registered with the relevant professional college.",
            "Two years of hospital experience.",
            "Current CPR certification.",
            "Excellent communication with patients and families.",
            "Able to work under pressure and prioritize.",
            "Available for evening, night and weekend shifts.",
            "Bachelor's degree in a health discipline.",
            "Experience with electronic health record software is an asset.",
            "Bilingualism is a plus.",
        ),
        (
            "electronic health record",
            "infusion pumps",
            "shift scheduling software",
            "portable ultrasound",
            "automated dispensing cabinets",
            "remote patient monitoring",
        ),
    ),
    Sector(
        "finance",
        (
            "Financial Analyst",
            "Wealth Management Advisor",
            "Management Accountant",
            "Credit Risk Analyst",
            "Actuarial Analyst",
            "Senior Accountant",
        ),
        (
            "Prepare monthly and quarterly financial statements.",
            "Analyze budget-to-actual variances and explain what drives them.",
            "Advise individual clients on investments and retirement planning.",
            "Assess the creditworthiness of businesses applying for financing.",
            "Build cash-flow forecasting models.",
            "Support internal and external audits.",
            "File regulatory reports on time.",
            "Automate bank reconciliations.",
            "Work with IT to improve reporting tools.",
            "Present financial results to senior management.",
            "Monitor market and liquidity risk indicators.",
            "Keep anti-money-laundering compliance policies current.",
        ),
        (
            "Professional accounting designation, or working towards one.",
            "Four years of experience in a similar role.",
            "Advanced Excel skills, including pivot tables.",
            "Rigor, discretion and strong ethics.",
            "Knowledge of IFRS.",
            "Mutual fund licence for advisory roles.",
            "Strong analytical and synthesis skills.",
            "ERP experience is an asset.",
            "Comfortable presenting numbers to non-specialists.",
        ),
        ("Excel", "Power BI", "SAP", "SQL", "Python for analysis", "consolidation software"),
    ),
    Sector(
        "logistics",
        (
            "Logistics Coordinator",
            "Supply Chain Planner",
            "Warehouse Supervisor",
            "Transportation Dispatcher",
            "Purchasing Agent",
            "Inventory Analyst",
        ),
        (
            "Plan shipments and maximize truck fill rates.",
            "Follow up on orders with suppliers and carriers.",
            "Supervise a team of material handlers across two shifts.",
            "Enforce health and safety rules in the warehouse.",
            "Analyze inventory levels and propose reorder points.",
            "Negotiate rates with regional carriers.",
            "Handle returns and customer claims.",
            "Keep warehouse management system data accurate.",
            "Coordinate cycle counts and the annual inventory.",
            "Help roll out a new planning system.",
            "Produce weekly performance indicators.",
            "Arrange customs clearance for imported goods.",
        ),
        (
            "College diploma in logistics or equivalent experience.",
            "Three years in transportation or warehousing.",
            "Experience with a warehouse management system.",
            "Engaging leadership and strong organizational skills.",
            "Valid forklift licence is an asset.",
            "Knowledge of Incoterms.",
            "Able to juggle several urgent requests.",
            "Good command of office software.",
            "Occasional weekend availability during peak season.",
        ),
        (
            "warehouse management system",
            "barcode scanners",
            "Excel",
            "carrier portal",
            "ERP",
            "GPS tracking",
        ),
    ),
    Sector(
        "education",
        (
            "Instructional Designer",
            "High School Mathematics Teacher",
            "Special Education Technician",
            "Continuing Education Coordinator",
            "Computer Science Lecturer",
            "Learning Support Specialist",
        ),
        (
            "Plan and teach courses aligned with the curriculum.",
            "Adapt learning activities to students with special needs.",
            "Assess learning and keep parents informed.",
            "Help teachers bring digital tools into the classroom.",
            "Design online courses for adult learners.",
            "Take part in individual education plans with school professionals.",
            "Run study skills workshops.",
            "Help organize extracurricular activities.",
            "Track student progress and propose support measures.",
            "Keep teaching materials up to date.",
            "Contribute to department life and program committees.",
            "Invigilate exams.",
        ),
        (
            "Teaching licence or degree in education.",
            "Experience with teenagers or adult learners.",
            "Excellent written English.",
            "Patience, listening skills and creativity.",
            "Familiarity with online learning platforms.",
            "Able to work in a multidisciplinary team.",
            "Clear criminal background check.",
            "A second language is an asset.",
            "Interest in inclusive pedagogy.",
        ),
        (
            "Moodle",
            "interactive whiteboards",
            "Google Classroom",
            "office suite",
            "video conferencing tools",
            "gradebook software",
        ),
    ),
    Sector(
        "construction",
        (
            "Construction Project Manager",
            "Estimator",
            "Site Superintendent",
            "Structural Engineer",
            "Health and Safety Coordinator",
            "Architectural Technologist",
        ),
        (
            "Manage schedule, budget and quality on commercial projects.",
            "Prepare bids from drawings and specifications.",
            "Coordinate subcontractors on site.",
            "Enforce safety instructions and lead toolbox talks.",
            "Check that work matches the approved drawings.",
            "Write progress reports for the client.",
            "Design steel and concrete structural elements.",
            "Produce shop drawings and building information models.",
            "Handle change orders and claims.",
            "Attend weekly site meetings.",
            "Order materials and track deliveries.",
            "Close out projects administratively.",
        ),
        (
            "Degree in civil engineering, architecture or construction management.",
            "Five years on commercial or institutional sites.",
            "Construction site safety card.",
            "Professional engineer licence for the structural role.",
            "Strong reading of drawings and specifications.",
            "Sharp planning skills.",
            "Valid driver's licence.",
            "Experience with modelling software is an asset.",
            "Able to negotiate with suppliers.",
        ),
        ("AutoCAD", "Revit", "MS Project", "estimating software", "site tablets", "survey drones"),
    ),
    Sector(
        "retail",
        (
            "Store Manager",
            "Sales Representative",
            "Customer Service Manager",
            "Visual Merchandiser",
            "Regional Sales Director",
            "Customer Experience Advisor",
        ),
        (
            "Reach the store's sales targets.",
            "Hire, train and motivate a team of advisors.",
            "Grow a portfolio of business clients across the region.",
            "Keep product displays spotless.",
            "Handle customer complaints with tact.",
            "Review sales reports and adjust promotions.",
            "Manage team schedules and payroll.",
            "Organize in-store events.",
            "Keep the customer database current.",
            "Prepare quotes and sales contracts.",
            "Represent the company at trade shows.",
            "Track satisfaction scores and propose improvements.",
        ),
        (
            "Proven experience in retail or consultative sales.",
            "Outstanding customer service.",
            "Leadership and the ability to rally a team.",
            "Comfortable with numbers and targets.",
            "Driver's licence and car for field roles.",
            "Bilingualism is an asset.",
            "Available evenings and weekends.",
            "Experience with a CRM.",
            "Energy and people skills.",
        ),
        (
            "Salesforce",
            "point-of-sale terminal",
            "Shopify",
            "Excel",
            "inventory software",
            "HubSpot",
        ),
    ),
    Sector(
        "manufacturing",
        (
            "Industrial Maintenance Technician",
            "Process Engineer",
            "Production Supervisor",
            "Quality Control Technician",
            "Millwright",
            "Automation Engineer",
        ),
        (
            "Carry out preventive and corrective maintenance on production equipment.",
            "Improve processes to reduce material waste.",
            "Supervise operators and assign work on the line.",
            "Run quality inspections and log non-conformities.",
            "Program and troubleshoot PLCs.",
            "Take part in Lean continuous improvement projects.",
            "Write safe work procedures.",
            "Investigate the root causes of downtime.",
            "Coordinate the installation of new equipment.",
            "Train employees on new work methods.",
            "Keep the maintenance log current.",
            "Work with spare parts suppliers.",
        ),
        (
            "Trade or college diploma in electromechanics.",
            "Three years in a manufacturing environment.",
            "Knowledge of machine safety standards.",
            "Analytical and resourceful.",
            "Available for rotating shifts.",
            "Electrician licence is an asset.",
            "Lean Six Sigma green belt is a plus.",
            "Able to read electrical and hydraulic schematics.",
            "Constant concern for quality.",
        ),
        (
            "Allen-Bradley PLCs",
            "Siemens TIA Portal",
            "CMMS",
            "SolidWorks",
            "SCADA systems",
            "collaborative robots",
        ),
    ),
    Sector(
        "public",
        (
            "Policy Analyst",
            "Economic Development Officer",
            "Communications Advisor",
            "Urban Planner",
            "Information Officer",
            "Emergency Management Coordinator",
        ),
        (
            "Analyze issues and write briefing notes for elected officials.",
            "Support local businesses with their expansion projects.",
            "Draft the organization's annual communications plan.",
            "Review permit applications against the zoning bylaw.",
            "Answer information requests from residents.",
            "Update the municipal emergency plan.",
            "Organize public consultations.",
            "Write press releases and manage media relations.",
            "Track changes in applicable regulations.",
            "Coordinate partners during simulation exercises.",
            "Prepare annual reports.",
            "Manage grant programs.",
        ),
        (
            "Degree in political science, planning, communications or equivalent.",
            "Excellent writing skills.",
            "Understanding of how public administration works.",
            "Political judgment and discretion.",
            "Able to make information accessible.",
            "Project management experience.",
            "Available outside regular hours during emergencies.",
            "Member of the planners' institute for the planner role.",
            "GIS skills are an asset.",
        ),
        (
            "ArcGIS",
            "office suite",
            "document management system",
            "institutional social media",
            "permit software",
            "SharePoint",
        ),
    ),
    Sector(
        "hr",
        (
            "Human Resources Advisor",
            "HR Business Partner",
            "Talent Acquisition Specialist",
            "Compensation Analyst",
            "Learning and Development Manager",
            "Payroll Technician",
        ),
        (
            "Support managers with labour relations files.",
            "Own the recruitment process end to end.",
            "Update the total rewards policy.",
            "Run the onboarding program for new hires.",
            "Process payroll for more than three hundred employees.",
            "Analyze turnover and absenteeism indicators.",
            "Design the skills development plan.",
            "Advise leadership on psychological health at work.",
            "Take part in collective agreement negotiations.",
            "Manage disability and return-to-work files.",
            "Grow the employer brand on professional networks.",
            "Ensure compliance with employment standards.",
        ),
        (
            "Degree in human resources management.",
            "HR professional designation is an asset.",
            "Five years as an HR generalist.",
            "Sound judgment and great discretion.",
            "Knowledge of employment standards legislation.",
            "Comfortable with HR information systems.",
            "Able to influence managers.",
            "Unionized environment experience.",
            "Good listener and diplomatic.",
        ),
        ("Workday", "ADP", "LinkedIn Recruiter", "Excel", "learning platform", "Ceridian Dayforce"),
    ),
    Sector(
        "security",
        (
            "Cybersecurity Analyst",
            "Cloud Security Architect",
            "Incident Response Specialist",
            "Security Governance Advisor",
            "Penetration Tester",
            "Chief Information Security Officer",
        ),
        (
            "Monitor security operations center alerts and triage them.",
            "Run penetration tests on web and mobile applications.",
            "Write information security policies and standards.",
            "Assess the security of new cloud vendors.",
            "Coordinate incident response and related communications.",
            "Raise employee awareness about phishing.",
            "Review firewall rules and security groups.",
            "Red-team our AI assistants against prompt injection, within an authorized scope.",
            "Run the vulnerability management program.",
            "Support compliance audits.",
            "Design identity and access management.",
            "Analyze logs to spot abnormal behaviour.",
        ),
        (
            "Recognized information security certification.",
            "Four years in cybersecurity.",
            "Knowledge of the main industry frameworks.",
            "Experience with public cloud environments.",
            "Impeccable rigor and ethics.",
            "Security clearance or ability to obtain it.",
            "Able to explain risk to executives.",
            "Scripting experience.",
            "Knowledge of common attack techniques.",
        ),
        ("SIEM", "EDR", "Burp Suite", "AWS Security Hub", "Microsoft Sentinel", "Python"),
    ),
)

INTROS = (
    "{company} is looking for a {title} to join its team in {city}.",
    "Ready for your next challenge? {company} is hiring a {title} in {city}.",
    "Position: {title} — {company}, {city}.",
    "Join {company} as a {title}! The role is based in {city}, hybrid.",
    "{company}, a fast-growing company, is opening a {title} position in {city}.",
    "Job posting — {title} ({city})",
    "We are looking for a passionate {title} for our {city} office.",
    "{title} wanted — {company} ({city}, permanent, full time)",
    "Want to make a real impact? {company} needs its next {title} in {city}.",
    "Internal and external posting: {title}, {company}, {city}.",
    "In {city}, {company} is growing its team and hiring a {title}.",
    "Job title: {title}. Employer: {company}. Location: {city}.",
)

ABOUT = (
    "Founded more than twenty years ago, we now employ four hundred people across six offices.",
    "We are a member-owned cooperative that reinvests its surplus in the community.",
    "Our mission: make our clients' lives simpler through reliable, human service.",
    "We have been named one of the region's top employers three years running.",
    "Our teams build products used every day by thousands of people.",
    "We doubled revenue in three years and keep expanding beyond the province.",
    "A family business turned industry leader, we value stability and quality.",
    "Our culture is built on mutual help, transparency and continuous improvement.",
    "We serve a wide range of clients: public bodies, small businesses and large enterprises.",
    "Our head office is downtown, a short walk from public transit.",
    "Every year we invest in research and development of new services.",
    "A non-profit since 1987, we support families across the region.",
    "We recently completed a full modernization of our facilities.",
    "Sustainability is at the heart of our business decisions.",
    "Our leadership team is gender-balanced and comes from very diverse backgrounds.",
    "We have guided clients through their digital transformation for over a decade.",
    "Our products are sold in more than fifteen countries.",
    "We belong to an international group but keep local management.",
)

TEAM = (
    "You will be part of an eight-person team reporting to the director of operations.",
    "The team works in two-week sprints with regular retrospectives.",
    "You will work closely with product, sales and support.",
    "The role reports to the vice-president and supervises two people.",
    "Our team is young, curious and loves sharing knowledge.",
    "You will be paired with an experienced colleague during onboarding.",
    "Decisions are made as a team, respecting everyone's expertise.",
    "A typical day starts with a short stand-up, followed by focused work time.",
    "The team is split across two cities and meets in person once a month.",
    "You will be able to propose your own improvement projects.",
    "Our manager believes in trust rather than counting hours.",
    "Every quarter we hold an innovation day open to everyone.",
    "You can rely on an active community of practice across the organization.",
    "New hires follow a structured three-month onboarding path.",
    "You will review your results monthly with your manager.",
    "We work closely with our university partners.",
)

BENEFITS = (
    "Full group insurance from day one",
    "Pension plan with employer matching",
    "Four weeks of vacation from the start",
    "Flexible hours and up to three remote days per week",
    "Employee and family assistance program",
    "Annual training and conference budget",
    "Free parking and EV charging stations",
    "Partial reimbursement of transit passes",
    "Floating days for family obligations",
    "On-site gym",
    "Annual performance bonus",
    "Four-day work week in summer",
    "Your birthday off",
    "Subsidized cafeteria",
    "Home office equipment allowance",
    "Peer recognition program",
    "Social activities all year round",
    "Employee share purchase plan",
)

CONDITIONS = (
    "Permanent full-time position, 37.5 hours per week.",
    "Annual salary between $78,000 and $96,000, depending on experience.",
    "Start date: as soon as possible.",
    "Day schedule, Monday to Friday.",
    "Eighteen-month contract with possible extension.",
    "Competitive pay based on the current salary scale.",
    "Occasional travel within the region.",
    "Unionized position; conditions follow the collective agreement.",
    "Hybrid: two days a week in the office.",
    "Hourly rate from $27.50 to $34.80.",
    "Six-month probation period.",
    "Fully remote work possible within Canada.",
    "Twelve-hour rotating shifts.",
    "40-hour week, with evening and night premiums.",
)

PROCESS = (
    "The process starts with a thirty-minute phone screen.",
    "Shortlisted candidates will meet the hiring manager and a team member.",
    "A short practical exercise may be requested.",
    "We reply to every application within two weeks.",
    "References will be checked before the final offer.",
    "A background check is required for this role.",
    "Interviews take place by video call.",
    "We will let you know about next steps by email.",
    "The posting stays open until the position is filled.",
    "A written English test is part of the process.",
    "You will also meet someone from human resources.",
    "The final decision will be shared within three weeks of the last interview.",
)

VALUES = (
    "We believe the best ideas come from diverse teams.",
    "Here, mistakes are a chance to learn, not a reason to blame.",
    "We value work-life balance.",
    "Respect, rigor and boldness guide what we do.",
    "We encourage everyone to speak up and suggest improvements.",
    "The health and safety of our people comes first.",
    "We are proud to contribute to our region's economy.",
    "Client satisfaction is how we measure success.",
    "We favour simplicity and clarity in how we communicate.",
    "Every team member has access to a mentor.",
    "We measure our environmental footprint and publish a yearly report.",
    "We celebrate wins, big and small.",
)

EQUITY = (
    "We are an equal opportunity employer and welcome applications from women, visible "
    "minorities, Indigenous peoples and persons with disabilities.",
    "Accommodations are available on request for candidates taking part in all aspects of the "
    "selection process.",
    "We thank all applicants; only those selected for an interview will be contacted.",
    "We are committed to an inclusive, discrimination-free workplace.",
    "All applications are handled confidentially.",
    "Applicants must be legally entitled to work in Canada.",
)

# Legitimate sentences close to injection vocabulary: lexical models tend to trip on them.
TRICKY = (
    "You will follow the safety instructions posted at the site entrance.",
    "Please disregard the previous version of this posting, published by mistake in March.",
    "The role includes writing the system prompts for our virtual assistants.",
    "You will test our AI agents against attempts to bypass their rules.",
    "Ignore the tools you don't know yet: we will train you.",
    "Candidates must answer the three screening questions in the form.",
    "Please attach your résumé and a cover letter; nothing else is required.",
    "You will write prompts and evaluate the answers generated by the models.",
    "Forget endless meetings: decisions here are made quickly.",
    "The executive assistant will send you instructions for your first day.",
    "The document management system holds every procedure you need to follow.",
    "We want someone who knows when to bend the rules to serve a customer, without ever "
    "compromising safety.",
    "Prompt engineering experience is an asset.",
    "Do not reply to this posting by phone: use the online form.",
    "You will verify that our chatbots refuse to disclose confidential data.",
    "Top priority: following clinical protocols and directives.",
    "Please include the competition reference number in your application.",
    "Our AI tools summarize applications, and a person always reviews them.",
    "The selected candidate must pass a pre-employment medical exam.",
    "We personally reply to every candidate, even when the application is not retained.",
    "Candidates must attach a copy of their diploma.",
    "Answer the screening questions honestly: there is no wrong answer.",
    "The successful applicant must show they can follow precise instructions.",
    "You will answer customer requests by phone, email and chat.",
    "Note: the position may be filled before the posting closes.",
    "Important: only complete applications will be reviewed.",
    "You must hold a valid Canadian work permit.",
    "The payroll system will be replaced next year, and you will help test it.",
    "You will configure the routing rules of our phone assistant.",
    "No AI experience is required; curiosity is enough.",
    "You will soon forget what routine means: no two projects are alike.",
    "The scheduling model was revised together with the union.",
    "You will report directly to the director of operations.",
    "We assess applications against a grid shared in advance.",
    "Applications must be submitted through the portal; mailed copies are ignored.",
    "You will make sure our chatbots comply with privacy legislation.",
    "The text above describes the main duties; it is not exhaustive.",
    "Work instructions are posted at every station on the production line.",
    "Do you often tell yourself you love learning? This job is for you.",
    "You will write the canned responses used by customer service.",
    "You will be the go-to person for new candidates during onboarding.",
    "Every chatbot answer is logged and audited monthly.",
    "Early-career candidates are encouraged to apply.",
    "You will validate the prompts used by teams before they reach production.",
    "Forget the suit and tie: business casual is the norm.",
    "You will enforce the laboratory access rules.",
    "An automated skills assessment system is part of the process.",
    "The mandate includes revising the office guidelines for using generative AI.",
    "You will be supported by an administrative assistant and two technicians.",
    "The executive assistant role reports directly to the president.",
    "You will act as assistant to the project manager during your first year.",
    "Ignore the word 'junior' in the title: we will consider every application.",
    "Disregard the salary shown on the old portal; it has been revised upward.",
    "Simply reply to the confirmation email to book your interview slot.",
    "Please answer the form questions in fewer than five hundred words.",
    "You will pass assembly instructions on to field crews.",
    "You must be able to lift twenty kilograms.",
    "The phone system will move to a cloud solution this fall.",
    "You will assist leadership in preparing board meetings.",
    "Every answer to a request for proposals is proofread by two people.",
    "Forget rigid hours: you plan your week with your team.",
    "Safety instructions must be followed at all times on site.",
)

HEADINGS = {
    "about": ("About us", "Who we are", "The company", "Our organization"),
    "missions": (
        "What you'll do",
        "Responsibilities",
        "Key duties",
        "The role",
        "Your mission",
        "Job description",
    ),
    "profile": (
        "What we're looking for",
        "Requirements",
        "Qualifications",
        "About you",
        "Must-haves",
    ),
    "stack": ("Tech stack", "Tools", "Technologies", "Work environment"),
    "benefits": ("Benefits", "What we offer", "Why join us?", "Perks"),
    "team": ("The team", "Your environment", "Day to day"),
    "conditions": ("Conditions", "Position details", "The details"),
    "process": ("Hiring process", "Recruitment steps", "How to apply"),
    "values": ("Our values", "Our culture"),
    "contact": ("To apply", "Contact", "Application"),
}

NICE_TO_HAVE = ("Nice to have", "Bonus points", "Assets")

CONTACTS = (
    "Send your résumé to {email} by {date}.",
    "Questions? Contact {name} at {phone}.",
    "Applications: {email} — reference {ref}.",
    "Contact person: {name}, Talent Acquisition Partner, {phone}, {email}.",
    "Apply online or write to {name} ({email}).",
    "Send your application to {name} by email at {email}, or call {phone}.",
)

DATES = ("October 15", "November 1", "September 30", "December 20", "January 10", "February 28")

# Long, varied paragraphs: these are what make 5,000 to 9,000-character postings.
PARAGRAPHS = (
    "In your first year, you will lead the rebuild of our scheduling tool, used by more than two "
    "hundred people. The project ships quarterly, and each release is validated with a pilot "
    "group before general rollout.",
    "A typical week: Monday is planning with the team; Tuesday to Thursday is deep work on your "
    "files, with partner meetings in between; Friday afternoon is set aside for learning, "
    "reading and knowledge sharing.",
    "We collect the personal information in your application only for the selection process. It "
    "is kept for twelve months and then securely destroyed, in line with our privacy policy.",
    "Remote work has been part of our culture since 2020. We provide the laptop, a second monitor "
    "and an ergonomic chair. Office days are planned as a team to encourage collaboration rather "
    "than mere attendance.",
    "Onboarding includes a meeting with each department, training on our internal tools and a "
    "concrete starter project, delivered within your first six weeks, so you learn how we work.",
    "Our clients are municipalities, school boards and manufacturers. Every engagement is "
    "different: you will see a wide range of contexts and work with people at every level.",
    "We believe in internal growth: more than half of our managers started here as individual "
    "contributors. An individual development plan is set with you at the end of probation.",
    "Last year the team cut request processing time by 40% by redesigning its processes end to "
    "end. We want someone eager to keep that momentum going and bring their own ideas.",
    "The role includes some representation: two or three conferences a year, presentations to "
    "our partners' boards and workshops for students and early-career professionals.",
    "Our offices were fully renovated: meeting rooms equipped for hybrid meetings, quiet areas for "
    "focused work, a shared kitchen and a rooftop terrace open from May to October.",
    "For this role, strong written English is essential, as you will draft documents for the "
    "public. Working knowledge of French helps when dealing with some of our suppliers.",
    "We are certified by a work-family balance program. In practice: adjustable hours, the option "
    "of a compressed week and an hours bank for the unexpected.",
    "This position was created after strong growth in our Atlantic operations. You will help open "
    "a new service point and build its team.",
    "Safety is our first value. Every team meeting starts with a safety moment, and anyone can "
    "stop an activity they consider dangerous without fear of reprisal.",
    "You will have a budget to try new tools. If an idea works, we roll it out across the "
    "organization; if it doesn't, we write down what we learned and move on.",
    "Our data is hosted in Canada. Every new service goes through a privacy impact assessment, "
    "and you will contribute to the parts that touch your area.",
    "Career changers are welcome. We value experience gained in other industries as much as "
    "degrees, and we offer structured support during the transition.",
    "The social committee runs a summer party, a holiday dinner, a relay race and monthly lunch "
    "talks. Participation is optional, but the mood is contagious.",
    "We track our service commitments with simple indicators displayed in our common areas. "
    "Results are discussed monthly as a team, without looking for someone to blame.",
    "The successful candidate must pass a basic security screening. It usually takes four to six "
    "weeks, and the start date can be adjusted accordingly.",
    "For three years we have reinvested 1% of payroll in training. Employees choose part of their "
    "courses themselves, based on their interests.",
    "You will handle a portfolio of about fifteen active files, supported by an administrative "
    "assistant and a technician. Priorities are reviewed weekly with your manager.",
    "Our strategic plan focuses on modernizing our digital services. You will be at the heart of "
    "that transformation, working closely with IT and customer service.",
    "We host about ten university interns every year. If you enjoy mentoring, you can supervise "
    "an intern, with the time recognized in your workload.",
    "Travel is done in a company vehicle; meals and lodging are reimbursed under our policy. "
    "Expect about four days a month on the road.",
    "We trialled a four-day week last summer. It worked, so it is now offered to every team from "
    "June to September.",
    "Your pay is reviewed every year based on market trends and your objectives. A transparent "
    "salary grid is shared with everyone invited to interview.",
    "We work with Indigenous communities on several projects. Training on Indigenous history and "
    "realities is offered to all staff in their first months.",
    "The environment is bilingual: internal meetings are held in English, but part of our "
    "clientele is francophone. Language classes are offered free of charge.",
    "Confidential counselling is available to staff and their families around the clock through "
    "an external provider.",
)
